### PR TITLE
Update settings.json

### PR DESCRIPTION
**Pull request by flovilmart**

### CODE REVIEW

**Comment by orta** [comment]
The duplicate messages is a tad worrying

**Comment by flovilmart** [comment]
effectively, I can try to pull the heroku logs

**Comment by flovilmart** [comment]
@orta the danger file effectively ran twice:

```
2017-07-01T19:38:01.279445+00:00 app[web.1]: info: [router] -  - passing to Dangerfile rule router
2017-07-01T19:38:01.280554+00:00 app[web.1]: info: [runner] - Event Settings: {
2017-07-01T19:38:01.280556+00:00 app[web.1]:  "commentableID": 1,
2017-07-01T19:38:01.280556+00:00 app[web.1]:  "hasRelatedCommentable": true,
2017-07-01T19:38:01.280557+00:00 app[web.1]:  "isRepoEvent": true,
2017-07-01T19:38:01.280557+00:00 app[web.1]:  "isTriggeredByUser": true,
2017-07-01T19:38:01.280558+00:00 app[web.1]:  "repo": {
2017-07-01T19:38:01.280559+00:00 app[web.1]:   "fullName": "parse-community/parse-community-peril",
2017-07-01T19:38:01.280559+00:00 app[web.1]:   "id": 111,
2017-07-01T19:38:01.280559+00:00 app[web.1]:   "installationID": 1,
2017-07-01T19:38:01.280560+00:00 app[web.1]:   "rules": {}
2017-07-01T19:38:01.280561+00:00 app[web.1]:  },
2017-07-01T19:38:01.280561+00:00 app[web.1]:  "repoName": "parse-community/parse-community-peril",
2017-07-01T19:38:01.280562+00:00 app[web.1]:  "triggeredByUsername": "flovilmart"
2017-07-01T19:38:01.280562+00:00 app[web.1]: }
2017-07-01T19:38:01.642945+00:00 app[web.1]: info: [runner] - Running Danger: got API? [object Object]
2017-07-01T19:38:02.947898+00:00 app[web.1]: Promise { null } 
2017-07-01T19:38:03.022617+00:00 app[web.1]: info: [runner] - Running Danger: got API? [object Object]
2017-07-01T19:38:04.002010+00:00 heroku[router]: at=info method=POST path="/webhook" host=peril-parse-community.herokuapp.com request_id=3498240c-52a7-4d25-8401-f5a5e3a54d2e fwd="192.30.252.34" dyno=web.1 connect=0ms service=2738ms status=200 bytes=216 protocol=https
2017-07-01T19:38:03.988830+00:00 app[web.1]: Promise { null }
2017-07-01T19:38:03.990379+00:00 app[web.1]: info: [runner] - Commenting, withresults:
2017-07-01T19:38:03.990380+00:00 app[web.1]: mds: 0
2017-07-01T19:38:03.990381+00:00 app[web.1]: mds: 0
2017-07-01T19:38:03.990382+00:00 app[web.1]: warns: 4
2017-07-01T19:38:03.990383+00:00 app[web.1]: fails: 0
2017-07-01T19:38:03.990383+00:00 app[web.1]:
2017-07-01T19:38:04.165922+00:00 app[web.1]: Request failed [403]: https://api.github.com/repos/parse-community/parse-community-peril/statuses/6bfe483dd5b8fd8904b010fb3b86d585d70b460f
2017-07-01T19:38:04.165996+00:00 app[web.1]:   "message": "Resource not accessible by integration",
2017-07-01T19:38:04.165995+00:00 app[web.1]: Response: {
2017-07-01T19:38:04.165997+00:00 app[web.1]:   "documentation_url": "https://developer.github.com/v3"
2017-07-01T19:38:04.165998+00:00 app[web.1]: }
2017-07-01T19:38:04.166164+00:00 app[web.1]: Found only warnings, not failing the build.
```

**Comment by orta** [comment]
👍

**Comment by steprescott** [comment]
I am seeing this issue too

```
2017-07-18T16:04:01.329589+00:00 app[web.1]: info: [runner] - Running Danger: got API? [object Object]
2017-07-18T16:04:04.573321+00:00 app[web.1]: info: [runner] - Running Danger: got API? [object Object]
2017-07-18T16:04:07.410923+00:00 app[web.1]: info: [runner] - Commenting, with results: 
2017-07-18T16:04:07.410939+00:00 app[web.1]: mds: 0
2017-07-18T16:04:07.410940+00:00 app[web.1]: messages: 2
2017-07-18T16:04:07.410941+00:00 app[web.1]: warns: 0
2017-07-18T16:04:07.410942+00:00 app[web.1]: fails: 0
```

**Comment by orta** [comment]
I just fixed the duped PR runs

**Pull request closed without merging**
